# Share the magnetic training setup and override the CrN data and non-SOC settings.
defaults:
  - soc_o2_mtace@_global_
  - _self_

dataset:
  train_file: ${oc.env:HOME}/dataset/CrN/collinear_CrN_train.xyz
  valid_file: ${oc.env:HOME}/dataset/CrN/collinear_CrN_val.xyz
  train_dataloader:
    batch_size: 4
  valid_dataloader:
    batch_size: 4
  shard_dirs:
    - ${oc.env:HOME}/dataset/CrN/graphCache

model:
  config:
    fidelity:
      - name: PBE
        atomic_energy: null
        magnetic_scale:
          7: 0.3
          24: 3.5
    angular_basis:
      use_spin_orbit_coupling: false
