# support resolver like add, sub, mul, float, ceil, floor
defaults:
  - _self_ 
  # # Specify the logger backlend
  # - config/logger@_here_: wandb
  # # Specify the model architecture
  # - config/model@model: e3nn

# Specify the path to resume training, Files must be end with .ckpt
resume_from_model: null

# Specify the model to be fine-tuned. Files must be end with .ckpt, .pt, or .pth
finetune_from_model: null 

finetune: null # this field equals ./finetune_config.yaml, auto read or write directly here

misc:
  project_name: Example
  global_seed: 42 
  device: cuda # cpu or cuda
  allow_tf32: true
  ignore_warning: true 
  log_level: debug # info or debug
  env: # You can specify here the environment variables that should always be used.
    WANDB_MODE: offline # For the convenience of Chinese users
  # Generally, there is no need to enable it. If training is unstable, prioritize using Layer Norm.
  LossSkipController:
    enable: false 
    manual_threshold: 1e6
    start_step: 1000
    ema_window: 1000
    multiplier: 1e6
    skip_nan: true
    skip_large: true

# # You can specify the logger here, for example, the built-in logger provided 
# # by Lightning or a third-party logger such as WandB. 
# logger:
#   _target_: pytorch_lightning.loggers.WandbLogger
#   project: ${misc.project_name} 
#   name: ${misc.project_name} 
#   # entity: xuzemin-nanjing-university 
#   log_model: final  # all, final
#   # tags: ["baseline", "v0.0.1"]
#   # group: "experiments"
#   save_dir: wandb_logs  

trainer:
  # As long as your system has NVIDIA GPUs, the following configuration will automatically detect and use all available GPUs for training.
  # If you wish to control which GPUs are visible, you can do so by setting the environment variable like export CUDA_VISIBLE_DEVICES=0,2. 
  _target_: lightning.Trainer
  num_nodes: 1   
  accelerator: auto
  devices: auto        # auto or list
  max_time: '90:00:00:00' # 90 days
  max_epochs: 20000
  min_epochs: 1        # null or int > 1
  precision: 32        # only 32 or 64 are allowed, not allow bf16, fp16 ....
  strategy: auto # For single-GPU/multi-node training, use auto
  # strategy: # Recommended for single-node training. 
  #   _target_: tace.utils.strategy.SimpleDDPStrategy                                                  
  gradient_clip_val: 10.0 
  enable_progress_bar: true # always set this to true to show progress_bar
  log_every_n_steps: 1000

  # Generally, no modification is required
  enable_model_summary: true
  enable_checkpointing: true 
  check_val_every_n_epoch: 1
  detect_anomaly: false
  inference_mode: false
  deterministic: false  
  # benchmark: true  

callbacks:
  early_stopping:
    _target_: lightning.pytorch.callbacks.EarlyStopping
    verbose: true
    log_rank_zero_only: true
    monitor: ${synth_metric.monitor_metric_name}
    # min_delta: 1e-5 
    patience: 50

  ema: # ema is always recommended
    _target_: tace.utils.callbacks.EMACallback
    decay: 0.999 # 0.99 - 0.999
    use_num_updates: true

  checkpoint_epoch: # at leas one checkpoint is required
    _target_: lightning.pytorch.callbacks.ModelCheckpoint
    dirpath: checkpoints_epoch
    filename: TACE-{${misc.project_name}-{epoch}-{step}-{${synth_metric.monitor_metric_name}:.4f}
    # monitor: ${synth_metric.monitor_metric_name}
    save_top_k: -1
    save_last: true
    every_n_epochs: 10
    # mode: min
    save_weights_only: false
    auto_insert_metric_name: false
    verbose: false

  # # If you also need to save checkpoints based on training steps, you can uncomment this section.
  # checkpoint_step: 
  #   _target_: lightning.pytorch.callbacks.ModelCheckpoint
  #   dirpath: checkpoints_step
  #   filename: TACE-{${misc.project_name}-{epoch}-{step}
  #   save_top_k: -1
  #   save_last: false
  #   every_n_train_steps: 10000
  #   save_weights_only: false
  #   auto_insert_metric_name: false
  #   verbose: false

dataset:
  type: ase # ase or ase-db
  split_seed: ${misc.global_seed} # this random seed is useful if auto split
  train_file: ../data/BaTiO3.xyz
  valid_file: null                
  # test_files: # (null, str, list) recoomend to use tace-eval --test 1 to print test errors to avoild possible bugs
  #   - dataset/test_300K.xyz
  #   - dataset/test_600K.xyz
  #   - dataset/test_1200K.xyz
  #   - dataset/test_dih.xyz
  valid_ratio: 0.1 # auto split from train file if valid file is null, The priority order is:  no_valid_set > valid_file > valid_from_index > ``valid_ratio.
  valid_from_index: false # split train and val from train.index and valid.index in current directory
  no_valid_set: false # The prerequisite for enabling this is that you are using a learning rate scheduler that does not depend on the validation set.
  neighborlist_backend: matscipy # [ase, matscipy, vesin, alchemiops] recommend matscipy
  storage_mode: memory # [memory, lmdb], if your dataset is large (> 100w), the recommended approach is to use lmdb, as this avoids repeatedly constructing the graph.  
  shard_dirs: # if lmdb model, specify a list of path where you save you graph
    - graphCache
  # If using LMDB mode, you must allocate a reasonable pre-storage size.  
  # Generally, if the number of neighboring atoms is around 60, about 200 KB per graph is sufficient.
  shard_size: 100000 # number of graphs stored per file in LMDB mode, should be large, here is just an example, if small, it will be slow and may be error
  cache_size: 1024 # cache for faster load data from dataloader
  avg_graph_size_in_KB: 200 # in KB, the total disk usage equals the size of this multiplied by the total number of your structures.
  lmdb_wait_timeout: 86400 # in seconds; when training with multi-GPU, the maximum waiting time.
  force_dtype: null # 32 or 64, if your data grapg saved in lmdb, but original float64, you can force to float32 for convenience
  keys: # all default value is the property name
    fidelity_idx_key: fidelity_idx
    energy_key: energy
    forces_key: forces
    stress_key: stress
    virials_key: virials
    charges_key: charges
    total_charge_key: total_charge
    direct_forces_key: forces
    direct_stress_key: stress
    direct_virials_key: virials
    polarization_key: polarization
    direct_dipole_key: dipole
    conservative_dipole_key: dipole
    direct_polarizability_key: polarizability
    conservative_polarizability_key: polarizability
    born_effective_charges_key: born_effective_charges
    electric_field_key: electric_field
    magnetic_field_key: magnetic_field
    initial_collinear_magmoms_key: initial_collinear_magmoms
    initial_noncollinear_magmoms_key: initial_noncollinear_magmoms
    final_collinear_magmoms_key: final_collinear_magmoms
    final_noncollinear_magmoms_key: final_noncollinear_magmoms
    total_collinear_magmoms_key: total_collinear_magmoms
    total_noncollinear_magmoms_key: total_noncollinear_magmoms
    collinear_magnetic_forces_key: collinear_magnetic_forces
    noncollinear_magnetic_forces_key: noncollinear_magnetic_forces

  train_dataloader:
    _target_: torch_geometric.loader.DataLoader
    batch_size: 4
    shuffle: true # always true
    drop_last: false
    num_workers: 4 # If the batch size is large, you need to set up multiple workers

  valid_dataloader:
    _target_: torch_geometric.loader.DataLoader
    batch_size: 2
    shuffle: false
    drop_last: false
    num_workers: 2 # If the batch size is large, you need to set up multiple workers

  test_dataloader: ${dataset.valid_dataloader}

optimizer:
  _target_: torch.optim.AdamW
  lr: 1e-3
  weight_decay: 1e-8
 
  # _target_: torch.optim.Adam
  # lr: 1e-3
  # weight_decay: 1e-8
  # amsgrad: true

  # # pip install pytorch-optimizer before use SOAP
  # _target_: pytorch_optimizer.SOAP
  # lr: 5e-3
  # betas: [0.95, 0.95]
  # weight_decay: 1e-3
  # precondition_frequency: 10
  # max_precondition_dim: 256
  # merge_dims: false
  # precondition_1d: false
  # normalize_gradient: false

  # # You must `export TACE_USE_MATRIX_WEIGHT=1` before use this optimizer
  # _target_: tace.utils.optimizer.HybridMuonOptimizer
  # lr: 1e-3
  # weight_decay: 1e-8
  # adam_betas: [0.9, 0.98]

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau # validaton-based
  mode: min
  factor: 0.5
  # min_lr: 1e-6
  patience: 25
  # threshold: 1e-4 
  extra:
    monitor: ${synth_metric.monitor_metric_name}
    interval: epoch
    frequency: 1

  # _target_: tace.utils.lr_scheduler.CosineAnnealingWarmupRestarts
  # first_cycle_steps: 400000 # total step, one batch = one step
  # cycle_mult: 1.0 # restart factor
  # max_lr: 2e-4 
  # min_lr: 2e-6
  # warmup_steps: ${floor:${mul:${scheduler.first_cycle_steps}, 0.05}} # 5 % first step (total here)
  # gamma: 1.0 # decay factor
  # last_epoch: -1
  # extra:
  #   interval: step
  #   frequency: 1

  # _target_: tace.utils.lr_scheduler.WarmupStableDecay
  # num_warmup_steps: 19691
  # num_stable_steps: 177219
  # num_decay_steps: 393820
  # min_lr_ratio: 0.001
  # num_cycles: 0.5
  # cooldown_type: cosine # [cosine, 1-sqrt, linear, 1-square]
  # extra:
  #   monitor: ${synth_metric.monitor_metric_name}
  #   interval: step
  #   frequency: 1

synth_metric: 
  # All metrics can be accessed by combining the stage (train | val) with the property name and the metric type (mae or rmse), for example:
  # val/energy_mae, val/energy_per_atom_rmse, val/forces_mae, val/stress_rmse, val/loss, train/loss ...
  # Specifically, we have a composite metric, val/synth_metric, for which we can specify a mixing ratio. This is particularly useful when training on large datasets with outliers.
  monitor_metric_name: val/synth_metric # use for variable interpolation
  # MAE
  val/energy_mae: 1.0
  val/energy_per_atom_mae: 5.0
  val/forces_mae: 5.0
  val/stress_mae: 2.5
  # RMSE
  val/energy_per_atom_rmse: 1.0
  val/forces_rmse: 1.0
  val/stress_rmse: 1.0

loss:
  # All physical quantity must follow a consistent order.
  _target_: tace.utils.loss.NormalLoss
  loss_property: [energy, forces, stress]
  loss_function_name: # prefix can be [mse, mae, huber, l2mae]
    - mse_energy_per_atom
    - mse_forces
    - mse_stress
  loss_property_weights: [1.0, 5.0, 0.5]
  loss_huber_delta: [0.01, 0.01, 0.01]

model:
  # export TACE_USE_OEQ=1 to use openequivariance, 0 to disable
  # export TACE_USE_CUE=1 to use cuequivariance, 0 to disable
  # export TACE_USE_EQT=1 to use equitorch, 0 to disable for correlation > 2

  # export TACE_USE_COMPILE=1 to use aoti, 0 to disable
  config:

    _target_: tace.models.e3nnTACE # [e3nnTACE] 
    wrapper:
      _target_: tace.models.TensorModel # [TensorModel]

    cutoff: 6.0 # (float), recommend 6.0
    max_neighbors: null # always null, we disable max_neighbors
    atomic_numbers: null # (null, list), null = read from dataset.
    
    fidelity:
      - {
        name: PBE, # (str) custom name
        atomic_energy: null # (null, Dict[int, float]), {1: -13.587222780835477, 6: -1029.4889999855063, 7: -1484.9814568572233, 8: -2041.9816003861047} 
      }

    node_embedding: 
      type: linear    # [linear, nonlinear, tensor, so2_tensor], linear is safer

    edge_embedding: 
      type: identity # identity  # [identity, linear, nonlinear, element2], identity is safer

    edge_update:
      type: element2  # [identity, element2], identity is safer

    mmax: 2 # Truncation for SO2 irreps, 3 is recommended.
    Lmax: 3 # Truncation for node, 2 is recommended.
    lmax: 3 # Truncation for edge, 3 is recommended.
    mag_Lmax: 1 # Maximum degree of magnetic solid harmonics, in [1, Lmax].
    num_layers: 3 # 2 for correlation >=3, can be higher when correlation=2
    num_channel: 64 # (int), 48~64, 64's accuracy is enough to achieve SOTA, never use channel > 64
    parity: false # (bool) in test, not for users, always false

    radial_basis:
      radial_basis: j0   # [j0, jn, gaussian]
      num_radial_basis: 8 # (int) 8-10 for j0 and jn, 8-64 for gaussian
      num_mag_radial_basis: 8 # magnetic Chebyshev basis for o3_w6j_mag and o2_mag
      distance_transform: null # [null, Agnesi, Soft], this plug-in from mace, if you do not know what it means, never use
      cutoff_fn: c2poly # [c2poly, c3poly, mollifier, cosine]
      polynomial_cutoff: 5 # (int)
      gaussian_width: 2.0
      order: 0 # (int), specify order for jn, for j0, it is negligible, for jn, <7 stable
      trainable: false # (bool)
      apply_cutoff: false # # (bool) true: cutoff was use in before radial_mlp, false: after radial_mlp
      hidden: [64, 64] # list(int)
      bias: true  # (bool)
      use_dydynamic_cutoff: false # in test, not for users
      dydynamic_cutoff_mu: 40     # in test, not for users
      r_min: 0.0                  # in test, not for users

    resnet: 
      type: BB # [BB, AB, BAB] A = atomic_basis, B = product_basis, control how resnet connect
      linear_type: identity # [aware, agnostic, identity]
      use_first_resnet: false

    layer_norm: # If training is unstable, prioritize specifying pre_norm_type. If it is still unstable, specify final_norm_type.
      pre_norm_type: null     # [merge_rms_norm, merge_layer_norm]
      final_norm_type: null   # [merge_rms_norm, merge_layer_norm]
      use_first_pre_norm: false 
          
    atomic_basis:
      type: [cgtp, uv_so2, uv_so2] # (str or list[str]) [cgtp, uu_so2, uv_so2, o3_w6j_mag, o2_mag]
      l1l2: null # [null, <=], restriction for each layer
      scatter_norm: avg_num_neighbors  # [avg_num_neighbors, density] density are from mace
      nonlinear: sigmoid_gate # [null, sigmoid_gate]
      edge_nonlinear: so2_sigmoid_gate # [null, so2_sigmoid_gate]
        
      # in test, not use
      node_wise_hidden: null
      edge_wise_hidden: null
      edge_ace_hidden: 32
      num_head: 4
      use_graph_softmax: true
      use_so2_edge_ace: true
      gate_m0: false
      scalar_act: null
      tensor_act: null
      use_radial_phase: false # false is recommend

    product_basis:
      type: cgtp  # (str or list[str]) [cgtp]
      l1l2: null  # [null, <=]
      correlation: 2 # (int) 3 is recommended for 2 layer, 2 is  is recommended for > 2 layer
      return_components: null # [null, list(int)], if not specify, last layer will only return target weight
      num_expert: null
      num_channel_per_expert: null
      nonlinear: silu_bilineargate # [null, silu_bilineargate]
      use_shared_expert: false
      agnostic: true

    readout_emlp:
      bias: false
      hidden: [16]
      use_alllayer: false # (bool) recommended true, if true, evergy layer has readout, else, only last layer has
      use_uie: false # (bool) whether use uie readout
    
    scale_shift:
      enable: true
      scale_type: rms_forces # [null, rms_forces, rms_forcesrms_forces_by_element]
      shift_type: null # [null, mean_delta_energy_per_atom, forces, mean_delta_energy_per_atom_by_element]
      scale_trainable: false # (bool) 
      shift_trainable: false # (bool) 
      all_atoms: false
      scale_zbl: false

    short_range:
      zbl: # metal units
        enable: false    # recommended true
        trainable: false # recommended always false

    long_range:
      les: # for introduction to the arguments, see the official repo: https://github.com/ChengUCB/les
        enable: false
        les_arguments:
          n_layers: 3
          n_hidden: [32, 16]
          add_linear_nn: true
          output_scaling_factor: 0.1
          sigma: 1.0
          dl: 2.0
          remove_self_interaction: true
          remove_mean: true
          epsilon_factor: 1.0
          use_atomwise: false
          compute_bec: false
          bec_output_index: null

    universal_embedding: 
      charges:
        enable: false

      total_charge:
        enable: false

      electric_field:
        enable: false
        normalizer: 1.0 # (float)

      magnetic_field:
        enable: false
        normalizer: 1.0 # (float)

      initial_noncollinear_magmoms:
        enable: false
        normalizer: 1.0 # (float)

    special: # this field can be thoroughly ignored if you only interested in E/F/S training
    
      charges:
        method: lagrangian # [lagrangian, uniform_distribution]

    # Unless you are traing foundation model, never use dropout
    # This is designed for direct pre-training
    dropout:  
      use_first_dropout: false
      stochastic_depth: 0.0
